import React from "react";
import Head from "next/head";
import { NextPage } from "next";
import FullLayout from "../components/FullLayout";
import AboutPage from "../components/AboutPage";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FullLayout>
        {/* <ProductPage /> */}
        <AboutPage />
      </FullLayout>
    </>
  );
};

export default About;
