import React from "react";
import Head from "next/head";
// Components
import { NextPage } from "next";
import FullLayout from "../components/FullLayout";
import ContactPage from "../components/ContactPage";

const Contact: NextPage = () => {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FullLayout>
        <ContactPage />
      </FullLayout>
    </>
  );
};

export default Contact;
