import React from "react";
import Head from "next/head";
import { NextPage } from "next";
import FullLayout from "../components/FullLayout";
import CounterPage from "../components/HomePage/components/Counter";

const Counter: NextPage = () => {
  return (
    <>
      <Head>
        <title>Counter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FullLayout>
        {/* <ProductPage /> */}
        <CounterPage />
      </FullLayout>
    </>
  );
};

export default Counter;
