import React from "react";
import Head from "next/head";
import { NextPage } from "next";
import FullLayout from "../components/FullLayout";
import Sliderpage from "../components/Slider";

const Slider: NextPage = () => {
  return (
    <>
      <Head>
        <title>Slider</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FullLayout>
        {/* <ProductPage /> */}
        <Sliderpage />
      </FullLayout>
    </>
  );
};

export default Slider;
