import React from "react";
import Head from "next/head";
import { NextPage } from "next";
import FullLayout from "../components/FullLayout";
import TeamMembers from "../components/Teammembers";

const Teammembers: NextPage = () => {
  return (
    <>
      <Head>
        <title>Team Members</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <FullLayout>
        {/* <ProductPage /> */}
        <TeamMembers />
      </FullLayout>
    </>
  );
};

export default Teammembers;
